name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar dependencias del Backend
        run: |
          source ~/.nvm/nvm.sh
          cd backend
          npm install --force

      - name: Inyectar variables de entorno Backend
        run: cp ~/backend.env ./backend/src/config/.env

      - name: Reiniciar Backend con PM2
        run: |
          source ~/.nvm/nvm.sh
          cd backend
          setsid pm2 restart api-backend || setsid pm2 start $GITHUB_WORKSPACE/backend/src/index.js --name "api-backend"
          pm2 save